---
# Apacheロールのデフォルト変数
wordpress_domain: "{{ lookup('env', 'WORDPRESS_DOMAIN') | default(lookup('env', 'DOMAIN_NAME') | default('example.com')) }}"
apache_user: apache
apache_group: apache
document_root: /var/www/html

# Apache設定
apache_modules:
  - rewrite
  - headers
  - ssl 