---
# WordPress設定のデフォルト値

# データベース設定
wp_db_name: "wordpress"
wp_db_user: "wordpress"
wp_db_password: "password"
wp_db_host: "localhost"

# WordPress設定
wp_table_prefix: "wp_"
wp_debug: false
wp_lang: "ja"

# セキュリティ設定
wp_automatic_updater_disabled: true
wp_disallow_file_edit: true
wp_disallow_file_mods: false

# メモリ設定
wp_memory_limit: "256M"
wp_max_memory_limit: "512M"

# パフォーマンス設定
wp_post_revisions: 5
wp_autosave_interval: 300
wp_empty_trash_days: 30

# 認証キー（本番環境では必ず変更してください）
wp_auth_key: "put your unique phrase here"
wp_secure_auth_key: "put your unique phrase here"
wp_logged_in_key: "put your unique phrase here"
wp_nonce_key: "put your unique phrase here"
wp_auth_salt: "put your unique phrase here"
wp_secure_auth_salt: "put your unique phrase here"
wp_logged_in_salt: "put your unique phrase here"
wp_nonce_salt: "put your unique phrase here" 