---
# PHPロールのデフォルト変数
php_memory_limit: 256M
php_max_execution_time: 300
php_max_input_time: 300
php_post_max_size: 64M
php_upload_max_filesize: 64M

# エラー設定
php_display_errors: 'Off'
php_log_errors: 'On'

# セッション設定
php_session_gc_maxlifetime: 1440
php_session_cookie_httponly: '1'

# セキュリティ設定
php_expose_php: 'Off'
php_allow_url_fopen: 'Off'
php_allow_url_include: 'Off'

# OPcache設定
php_opcache_enable: '1'
php_opcache_memory_consumption: 128
php_opcache_interned_strings_buffer: 8
php_opcache_max_accelerated_files: 4000
php_opcache_revalidate_freq: 2
php_opcache_fast_shutdown: '1'

# 日付設定
php_date_timezone: 'Asia/Tokyo'

# PHP-FPM設定
php_fpm_enabled: true 