---
# WordPress設定タスク
- name: Download WordPress
  get_url:
    url: https://ja.wordpress.org/latest-ja.zip
    dest: /tmp/wordpress.zip
    mode: '0644'
  become: yes

- name: Extract WordPress
  unarchive:
    src: /tmp/wordpress.zip
    dest: /tmp/
    remote_src: yes
  become: yes

- name: Copy WordPress files to document root
  copy:
    src: /tmp/wordpress/
    dest: /var/www/html/
    mode: '0644'
    owner: apache
    group: apache
    remote_src: yes
  become: yes
  notify: restart apache

- name: Configure WordPress wp-config.php
  template:
    src: wp-config.php.j2
    dest: /var/www/html/wp-config.php
    mode: '0644'
    owner: apache
    group: apache
  become: yes
  notify: restart apache

- name: Configure WordPress .htaccess
  template:
    src: .htaccess.j2
    dest: /var/www/html/.htaccess
    mode: "{{ wp_htaccess_mode }}"
    owner: "{{ wp_htaccess_owner }}"
    group: "{{ wp_htaccess_group }}"
  become: yes
  notify: restart apache

- name: Set proper permissions for .htaccess file
  file:
    path: /var/www/html/.htaccess
    mode: "0664"
    owner: "{{ wp_htaccess_owner }}"
    group: "{{ wp_htaccess_group }}"
  become: yes
  notify: restart apache

- name: Ensure .htaccess file is writable by web server
  file:
    path: /var/www/html/.htaccess
    mode: "0664"
    owner: "{{ wp_htaccess_owner }}"
    group: "{{ wp_htaccess_group }}"
  become: yes
  notify: restart apache

- name: Set proper permissions for WordPress files
  file:
    path: /var/www/html
    state: directory
    mode: '0755'
    owner: apache
    group: apache
    recurse: yes
  become: yes

- name: Ensure .htaccess directory has correct permissions
  file:
    path: /var/www/html
    mode: '0755'
    owner: apache
    group: apache
  become: yes

- name: Set proper permissions for wp-content directory
  file:
    path: /var/www/html/wp-content
    state: directory
    mode: '0755'
    owner: apache
    group: apache
    recurse: yes
  become: yes

- name: Set proper permissions for wp-uploads directory
  file:
    path: /var/www/html/wp-content/uploads
    state: directory
    mode: '0755'
    owner: apache
    group: apache
    recurse: yes
  become: yes

- name: Ensure .htaccess file has correct permissions for WordPress
  file:
    path: /var/www/html/.htaccess
    mode: "{{ wp_htaccess_mode }}"
    owner: "{{ wp_htaccess_owner }}"
    group: "{{ wp_htaccess_group }}"
  become: yes
  notify: restart apache

- name: Clean up temporary files
  file:
    path: /tmp/wordpress.zip
    state: absent
  become: yes

- name: Clean up temporary directory
  file:
    path: /tmp/wordpress
    state: absent
  become: yes

# データベース設定の実行
- name: Include database setup tasks
  include_tasks: database_setup.yml
  when: wp_db_name is defined and wp_db_host is defined 