---
# WordPress設定タスク
- name: Create WordPress directory
  file:
    path: /var/www/html
    state: directory
    mode: '0755'
    owner: apache
    group: apache
  become: yes

- name: Download Japanese WordPress
  get_url:
    url: https://ja.wordpress.org/latest-ja.tar.gz
    dest: /tmp/wordpress.tar.gz
    mode: '0644'
    timeout: 300
  become: yes

- name: Extract WordPress
  unarchive:
    src: /tmp/wordpress.tar.gz
    dest: /tmp/
    remote_src: yes
  become: yes

- name: Copy WordPress files to document root
  copy:
    src: /tmp/wordpress/
    dest: /var/www/html/
    remote_src: yes
    owner: apache
    group: apache
    mode: '0755'
  become: yes

- name: Set correct permissions for WordPress
  file:
    path: /var/www/html
    owner: apache
    group: apache
    recurse: yes
  become: yes

- name: Configure wp-config.php from template
  template:
    src: wp-config.php.j2
    dest: /var/www/html/wp-config.php
    owner: apache
    group: apache
    mode: '0644'
  become: yes
  notify: restart apache

- name: Clean up temporary files
  file:
    path: /tmp/wordpress.tar.gz
    state: absent
  become: yes

- name: Clean up temporary directory
  file:
    path: /tmp/wordpress
    state: absent
  become: yes

- name: Set WordPress language to Japanese
  lineinfile:
    path: /var/www/html/wp-config.php
    regexp: "define\\( 'WPLANG', '.*' \\);"
    line: "define( 'WPLANG', '{{ wordpress_locale | default('ja') }}' );"
    state: present
  become: yes
  notify: restart apache

- name: Create wp-content/languages directory
  file:
    path: /var/www/html/wp-content/languages
    state: directory
    mode: '0755'
    owner: apache
    group: apache
  become: yes

- name: Set correct permissions for languages directory
  file:
    path: /var/www/html/wp-content/languages
    owner: apache
    group: apache
    recurse: yes
  become: yes 