all:
  children:
    wordpress:
      hosts:
        wordpress_ec2:
          ansible_host: 54.178.41.253
          ansible_user: ec2-user
          ansible_ssh_private_key_file: ~/.ssh/id_ed25519
          ansible_ssh_common_args: -o StrictHostKeyChecking=no
    nat_instance:
      hosts:
        nat_ec2:
          ansible_host: 35.73.60.169
          ansible_user: ec2-user
          ansible_ssh_private_key_file: ~/.ssh/id_ed25519
          ansible_ssh_common_args: -o StrictHostKeyChecking=no
