all:
  children:
    wordpress:
      hosts:
        wordpress_ec2:
          ansible_host: 54.64.49.220
          ansible_user: ec2-user
          ansible_ssh_private_key_file: ~/.ssh/wp-shamo-ssh-key
          ansible_ssh_common_args: -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null
          ansible_ssh_extra_args: -o ConnectTimeout=30
    nat_instance:
      hosts:
        nat_ec2:
          ansible_host: 54.64.109.28
          ansible_user: ec2-user
          ansible_ssh_private_key_file: ~/.ssh/wp-shamo-ssh-key
          ansible_ssh_common_args: -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null
          ansible_ssh_extra_args: -o ConnectTimeout=30
