all:
  children:
    wordpress:
      hosts:
        wordpress_ec2:
          ansible_host: 57.181.5.47
          ansible_user: ec2-user
          ansible_ssh_private_key_file: ~/.ssh/id_rsa
          ansible_ssh_common_args: -o StrictHostKeyChecking=no
    nat_instance:
      hosts:
        nat_ec2:
          ansible_host: 18.176.187.78
          ansible_user: ec2-user
          ansible_ssh_private_key_file: ~/.ssh/id_rsa
          ansible_ssh_common_args: -o StrictHostKeyChecking=no
