---
# 本番環境設定
environment: production
debug_mode: false

# データベース設定
wordpress_db_host: "{{ rds_endpoint }}"
wordpress_db_name: wordpress
wordpress_db_user: wordpress
wordpress_db_password: "{{ db_password }}"

# セキュリティ設定
wordpress_debug: false
wordpress_automatic_updater_disabled: true
wordpress_disallow_file_edit: true
wordpress_disallow_file_mods: true

# 監視設定
monitoring_enabled: true
alert_email: admin@example.com
monitoring_interval_hours: 6

# ログ設定
log_level: info
log_retention_days: 30 