---
# 本番環境設定
environment: production
debug_mode: false

# データベース設定
wp_db_host: "{{ lookup('env', 'WORDPRESS_DB_HOST') | default('localhost') }}"
wp_db_name: wordpress
wp_db_user: wordpress
wp_db_password: "{{ lookup('env', 'WORDPRESS_DB_PASSWORD') | default('password') }}"

# セキュリティ設定
wordpress_debug: false
wordpress_automatic_updater_disabled: true
wordpress_disallow_file_edit: true
wordpress_disallow_file_mods: true

# 監視設定
monitoring_enabled: true
alert_email: admin@example.com
monitoring_interval_hours: 6

# ログ設定
log_level: info
log_retention_days: 30 