---
- name: SSL Setup for WordPress
  hosts: wordpress
  become: yes
  gather_facts: yes
  
  vars_files:
    - ../group_vars/all.yml
    - ../group_vars/wordpress.yml
  
  tasks:
    - name: Check ACM certificate status
      uri:
        url: "https://acm.us-east-1.amazonaws.com/"
        method: POST
        headers:
          Content-Type: application/x-amz-json-1.1
          X-Amz-Target: CertificateManager.DescribeCertificate
        body: |
          {
            "CertificateArn": "arn:aws:acm:us-east-1:827006371271:certificate/512cedc8-b3cd-43fe-a2fd-47d7130a19ba"
          }
      register: cert_status
      delegate_to: localhost
      ignore_errors: yes
    
    - name: Wait for certificate validation
      uri:
        url: "https://acm.us-east-1.amazonaws.com/"
        method: POST
        headers:
          Content-Type: application/x-amz-json-1.1
          X-Amz-Target: CertificateManager.DescribeCertificate
        body: |
          {
            "CertificateArn": "arn:aws:acm:us-east-1:827006371271:certificate/512cedc8-b3cd-43fe-a2fd-47d7130a19ba"
          }
      register: cert_status
      delegate_to: localhost
      until: cert_status.json.Certificate.Status == "ISSUED"
      retries: 30
      delay: 60
    
    - name: Include Apache role for SSL setup
      include_role:
        name: apache
    
    - name: Include Security role for SSL security
      include_role:
        name: security
    
    - name: Test HTTPS connection
      uri:
        url: "https://{{ wordpress_domain }}"
        method: GET
        validate_certs: no
      register: https_test
      ignore_errors: yes
    
    - name: Display HTTPS test result
      debug:
        msg: "HTTPS connection test: {{ https_test.status }}"
      when: https_test is defined
