---
# SSL設定プレイブック（ACM証明書検証完了後に実行）
- name: SSL Setup for WordPress
  hosts: wordpress
  become: yes
  gather_facts: yes
  
  vars:
    wordpress_force_ssl: true
    wordpress_ssl_admin: true
  
  tasks:
    - name: Check ACM certificate status via AWS CLI
      shell: |
        aws acm describe-certificate \
          --certificate-arn "arn:aws:acm:us-east-1:827006371271:certificate/e7f1760d-fafe-43e4-b40d-e231b33c7ed3" \
          --region us-east-1 \
          --query 'Certificate.Status' \
          --output text
      register: cert_status
      delegate_to: localhost
      ignore_errors: yes
    
    - name: Display certificate status
      debug:
        msg: "ACM Certificate Status: {{ cert_status.stdout | default('Unknown') }}"
    
    - name: Wait for certificate to be issued
      shell: |
        aws acm describe-certificate \
          --certificate-arn "arn:aws:acm:us-east-1:827006371271:certificate/e7f1760d-fafe-43e4-b40d-e231b33c7ed3" \
          --region us-east-1 \
          --query 'Certificate.Status' \
          --output text
      register: cert_status
      delegate_to: localhost
      until: cert_status.stdout == "ISSUED"
      retries: 30
      delay: 60
      ignore_errors: yes
    
    - name: Update WordPress SSL settings
      template:
        src: ../roles/wordpress/templates/wp-config.php.j2
        dest: /var/www/html/wp-config.php
        owner: apache
        group: apache
        mode: '0644'
      become: yes
      notify: restart apache
    
    - name: Enable HTTPS redirect in Apache
      replace:
        path: /etc/httpd/conf.d/wordpress.conf
        regexp: '^    # RewriteEngine On'
        replace: '    RewriteEngine On'
      become: yes
      notify: restart apache
    
    - name: Enable HTTPS redirect rules
      replace:
        path: /etc/httpd/conf.d/wordpress.conf
        regexp: '^    # RewriteCond %{HTTPS} off'
        replace: '    RewriteCond %{HTTPS} off'
      become: yes
      notify: restart apache
    
    - name: Enable HTTPS redirect rule
      replace:
        path: /etc/httpd/conf.d/wordpress.conf
        regexp: '^    # RewriteRule \^\(\.\*\)\$ https://%{HTTP_HOST}%{REQUEST_URI} \[L,R=301\]'
        replace: '    RewriteRule ^(.*)$ https://%{HTTP_HOST}%{REQUEST_URI} [L,R=301]'
      become: yes
      notify: restart apache
    
    - name: Enable HSTS header
      replace:
        path: /etc/httpd/conf.d/wordpress.conf
        regexp: '^        # Header always set Strict-Transport-Security'
        replace: '        Header always set Strict-Transport-Security'
      become: yes
      notify: restart apache
    
    - name: Enable HTTPS VirtualHost
      replace:
        path: /etc/httpd/conf.d/wordpress.conf
        regexp: '^# <VirtualHost \*:443>'
        replace: '<VirtualHost *:443>'
      become: yes
      notify: restart apache
    
    - name: Enable HTTPS VirtualHost closing
      replace:
        path: /etc/httpd/conf.d/wordpress.conf
        regexp: '^# </VirtualHost>'
        replace: '</VirtualHost>'
      become: yes
      notify: restart apache
    
    - name: Enable SSL Engine
      replace:
        path: /etc/httpd/conf.d/wordpress.conf
        regexp: '^#     SSLEngine on'
        replace: '    SSLEngine on'
      become: yes
      notify: restart apache
    
    - name: Enable SSL Certificate File
      replace:
        path: /etc/httpd/conf.d/wordpress.conf
        regexp: '^#     SSLCertificateFile /etc/ssl/certs/wordpress.crt'
        replace: '    SSLCertificateFile /etc/ssl/certs/wordpress.crt'
      become: yes
      notify: restart apache
    
    - name: Enable SSL Certificate Key File
      replace:
        path: /etc/httpd/conf.d/wordpress.conf
        regexp: '^#     SSLCertificateKeyFile /etc/ssl/private/wordpress.key'
        replace: '    SSLCertificateKeyFile /etc/ssl/private/wordpress.key'
      become: yes
      notify: restart apache
    
    - name: Enable SSL Certificate Chain File
      replace:
        path: /etc/httpd/conf.d/wordpress.conf
        regexp: '^#     SSLCertificateChainFile /etc/ssl/certs/wordpress-chain.crt'
        replace: '    SSLCertificateChainFile /etc/ssl/certs/wordpress-chain.crt'
      become: yes
      notify: restart apache
    
    - name: Test HTTPS connection
      uri:
        url: "https://{{ ansible_default_ipv4.address | default(wordpress_domain) }}"
        method: GET
        validate_certs: no
      register: https_test
      ignore_errors: yes
    
    - name: Display HTTPS test result
      debug:
        msg: "HTTPS connection test: {{ https_test.status if https_test is defined else 'Not tested' }}"
