---
# WordPress設定更新プレイブック
- name: Update WordPress configuration
  hosts: wordpress
  become: yes
  
  vars:
    db_password: "{{ lookup('env', 'WORDPRESS_DB_PASSWORD') | default('your-secure-password-here') }}"
  
  tasks:
    - name: Update WordPress URLs in wp-config.php
      replace:
        path: /var/www/html/wp-config.php
        regexp: "define\\( 'WP_HOME', '.*' \\);"
        replace: "define( 'WP_HOME', 'https://{{ wordpress_domain | default(cloudfront_domain | default('example.com')) }}' );"
      notify: restart apache

    - name: Update WordPress SITEURL in wp-config.php
      replace:
        path: /var/www/html/wp-config.php
        regexp: "define\\( 'WP_SITEURL', '.*' \\);"
        replace: "define( 'WP_SITEURL', 'https://{{ wordpress_domain | default(cloudfront_domain | default('example.com')) }}' );"
      notify: restart apache

    - name: Update WordPress URLs in database
      mysql_query:
        login_db: wordpress
        login_host: "{{ rds_endpoint | regex_replace(':.*', '') }}"
        login_port: "{{ rds_endpoint | regex_replace('.*:', '') | default('3306') }}"
        login_user: admin
        login_password: "{{ db_password }}"
        query: "UPDATE wp_options SET option_value = 'https://{{ wordpress_domain | default(cloudfront_domain | default('example.com')) }}' WHERE option_name IN ('home', 'siteurl');"
      ignore_errors: yes

  handlers:
    - name: restart apache
      service:
        name: httpd
        state: restarted
