---
# WordPress環境構築プレイブック（CloudFront対応版）
- name: Setup WordPress environment
  hosts: wordpress
  become: yes
  vars:
    wordpress_db_host: "{{ lookup('env', 'WORDPRESS_DB_HOST') | default('localhost') }}"
    wordpress_db_name: wordpress
    wordpress_db_user: admin
    wordpress_db_password: "{{ lookup('env', 'WORDPRESS_DB_PASSWORD') | default('password') }}"
    wordpress_config_auto: true
    ssh_private_key: "{{ lookup('file', '/tmp/terraform_ssh_key') }}"
    ssh_public_key: "{{ lookup('file', '/tmp/terraform_ssh_key.pub') | default('') }}"
  
  roles:
    - system
    - database
    - apache
    - php
    - security
    - wordpress

- name: Configure SSH for all servers
  hosts: all
  become: yes
  vars:
    ssh_private_key: "{{ lookup('file', '/tmp/terraform_ssh_key') }}"
    ssh_public_key: "{{ lookup('file', '/tmp/terraform_ssh_key.pub') | default('') }}"
  roles:
    - ssh 