---
# WordPress環境構築プレイブック
- name: Setup WordPress environment
  hosts: wordpress
  become: yes
  vars:
    wordpress_db_host: "{{ lookup('env', 'WORDPRESS_DB_HOST') | default('localhost') }}"
    wordpress_db_name: wordpress
    wordpress_db_user: wordpress
    wordpress_db_password: "{{ lookup('env', 'WORDPRESS_DB_PASSWORD') | default('password') }}"
    wordpress_config_auto: true
  
  roles:
    - system
    - database
    - apache
    - php
    - security
    - wordpress

- name: Configure SSH for all servers
  hosts: all
  become: yes
  roles:
    - ssh 