---
# WordPress環境構築プレイブック
- name: Setup WordPress environment
  hosts: wordpress
  become: yes
  vars:
    wordpress_db_host: "{{ rds_endpoint }}"
    wordpress_db_name: wordpress
    wordpress_db_user: wordpress
    wordpress_db_password: "{{ db_password }}"
    wordpress_config_auto: true
  
  roles:
    - system
    - apache
    - php
    - security
    - wordpress

- name: Configure SSH for all servers
  hosts: all
  become: yes
  roles:
    - ssh 