---
# WordPress環境構築プレイブック（CloudFront対応版）
- name: Setup WordPress environment
  hosts: wordpress
  become: yes
  vars:
    # データベース設定
    wp_db_host: "{{ lookup('env', 'WORDPRESS_DB_HOST') | default('localhost') }}"
    wp_db_name: wordpress
    wp_db_user: wordpress
    wp_db_password: "{{ lookup('env', 'WORDPRESS_DB_PASSWORD') | default('password') }}"
    
    # WordPress設定
    wordpress_domain: "{{ lookup('env', 'WORDPRESS_DOMAIN') | default('example.com') }}"
    
    # SSH設定
    ssh_private_key: "{{ lookup('env', 'SSH_PRIVATE_KEY_PATH') | default('/tmp/wp-sample-key.pem') }}"
    ssh_public_key: "{{ lookup('env', 'SSH_PUBLIC_KEY_PATH') | default('/tmp/wp-sample-key.pub') }}"
    
    # PHP-FPM設定
    php_fpm_enabled: true
    
    # Apache設定
    apache_enable_ssl: false  # CloudFrontがHTTPSを処理
    
    # セキュリティ設定
    security_enable_firewall: true
    security_enable_selinux: true
  
  roles:
    - system
    - database
    - apache
    - php
    - security
    - wordpress

- name: Configure SSH for all servers
  hosts: all
  become: yes
  vars:
    ssh_private_key: "{{ lookup('env', 'SSH_PRIVATE_KEY_PATH') | default('/tmp/wp-sample-key.pem') }}"
    ssh_public_key: "{{ lookup('env', 'SSH_PUBLIC_KEY_PATH') | default('/tmp/wp-sample-key.pub') }}"
  roles:
    - ssh 