---
# セキュリティ設定タスク
- name: Install security packages
  dnf:
    name:
      - fail2ban
      - rkhunter
      - chkrootkit
    state: present
  become: yes

- name: Configure firewall (firewalld)
  firewalld:
    port: "{{ item }}"
    permanent: yes
    state: enabled
  loop:
    - 22/tcp
    - 80/tcp
    - 443/tcp
  become: yes

- name: Configure SELinux for Apache
  seboolean:
    name: httpd_can_network_connect
    state: yes
    persistent: yes
  become: yes

- name: Set SELinux context for WordPress
  sefcontext:
    target: '/var/www/html(/.*)?'
    setype: httpd_sys_rw_content_t
    state: present
  become: yes

- name: Apply SELinux context changes
  command: restorecon -Rv /var/www/html
  become: yes
  ignore_errors: yes

- name: Configure fail2ban
  template:
    src: jail.local.j2
    dest: /etc/fail2ban/jail.local
    mode: '0644'
  become: yes
  notify: restart fail2ban

- name: Enable and start fail2ban
  service:
    name: fail2ban
    state: started
    enabled: yes
  become: yes

- name: Configure system security settings
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    state: present
  loop:
    - { regexp: '^#?PermitRootLogin', line: 'PermitRootLogin no' }
    - { regexp: '^#?MaxAuthTries', line: 'MaxAuthTries 3' }
    - { regexp: '^#?ClientAliveInterval', line: 'ClientAliveInterval 300' }
    - { regexp: '^#?ClientAliveCountMax', line: 'ClientAliveCountMax 2' }
  become: yes
  notify: restart sshd 